apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncaaprsapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ncaaprsapi
  template:
    metadata:
      labels:
        app: ncaaprsapi
    spec:
      serviceAccountName: ncaaprsapi-ksa
      containers:
        - name: ncaaprsapi
          image: us-central1-docker.pkg.dev/ncaaprsapi/ncaaprsapi/ncaaprsapi:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

